apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      # Since we attached the IAM role to the GCE instance,
      # ESO will automatically authenticate using the node's Workload Identity / Metadata Server.
      projectID: "{{ .Values.gcpProjectId }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cartwright-postgres-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: cartwright-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: cartwright-postgres-password
