apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifier
  labels:
    app: notifier
spec:
  ports:
    - port: 50052
      targetPort: 50052
      protocol: TCP
      name: grpc
  selector:
    app: notifier
  type: ClusterIP
